### ISSUE TITLE
Wireframe turn based game

### ISSUE THREAD

**Issue by shoriminimoe** [shoriminimoe/electric-elves#4]
- [x] two players on board move independently
- [x] Each movement sends position updates to server
- [x] Client is Input only (player movement)

**Comment by ChaseParate** [comment]
Basic Client/Server Model
![Basic Server Model Image](https://user-images.githubusercontent.com/97500441/180631409-63da7cdb-97a8-4882-b042-ca3f7ba072f5.png)

**Comment by ChaseParate** [comment]
I'll do the front-end pygame window

**Comment by shoriminimoe** [comment]
Completed by #26 and #27
